# Generated by Django 4.0.1 on 2022-03-21 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingwonder', '0003_rename_category_category_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='date',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='status',
        ),
        migrations.AddField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='salesorderlineitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_order_line_items', to='shoppingwonder.product'),
        ),
        migrations.AlterField(
            model_name='salesorderlineitem',
            name='sales_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_order_line_items', to='shoppingwonder.salesorder'),
        ),
        migrations.CreateModel(
            name='SalesOrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Cancelled'), (1, 'Ordered'), (2, 'Paid'), (3, 'Shipped'), (4, 'Delivered')], default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_order_status', to='shoppingwonder.salesorder')),
            ],
        ),
    ]
