# Generated by Django 4.0.1 on 2022-03-21 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingwonder', '0004_alter_category_options_remove_salesorder_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesorderstatus',
            options={'verbose_name_plural': 'Sales order statuses'},
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='cost',
            new_name='unit_cost',
        ),
    ]
