# Generated by Django 4.0.1 on 2022-03-21 17:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingwonder', '0005_alter_salesorderstatus_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorderlineitem',
            name='stocks',
            field=models.ManyToManyField(related_name='sales_order_line_items', to='shoppingwonder.Stock'),
        ),
        migrations.AddField(
            model_name='stock',
            name='available_for_sales',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
