# Generated by Django 4.0.1 on 2022-03-26 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingwonder', '0006_salesorderlineitem_stocks_stock_available_for_sales_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sold',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='views',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
