# Generated by Django 4.0.1 on 2022-03-26 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingwonder', '0007_product_sold_product_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='imageURL',
            field=models.URLField(max_length=1024),
        ),
    ]
