# Generated by Django 4.0.1 on 2022-03-26 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingwonder', '0008_alter_image_imageurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='best_seller',
        ),
        migrations.RemoveField(
            model_name='product',
            name='new',
        ),
    ]
