# Generated by Django 4.0.1 on 2022-03-31 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingwonder', '0012_remove_product_instruction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='views',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
