# Generated by Django 4.0.1 on 2022-04-02 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingwonder', '0013_alter_product_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available_for_sales',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
