# Generated by Django 4.0.3 on 2022-04-02 16:52

from django.db import migrations
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingwonder', '0015_rename_available_for_sales_product_remaining_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='details',
            field=martor.models.MartorField(blank=True),
        ),
    ]
