# Generated by Django 4.0.3 on 2022-04-09 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingwonder', '0021_remove_cartitem_created_cartitem_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='remaining_qty',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='sold',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
