# Generated by Django 4.0.3 on 2022-04-09 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingwonder', '0022_alter_product_remaining_qty_alter_product_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='minQty',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
